version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: zimalab_test_app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
  
  nginx:
    image: nginx:latest
    container_name: zimalab_test_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/ini/nginx-ini:/etc/nginx/conf.d

  mysql:
    image: mysql:8.0
    environment:

      - MYSQL_DATABASE=zimalab_test 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword

    volumes:
      - ./docker/data/db-data:/var/lib/mysql
      - ./docker/ini/db-ini:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  db-data: ~